In [88]:
import pandas as pd
csv_df=pd.read_csv('cars.csv', delimiter=";")

csv_df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8,307.0,130.0,3504.0,12.0,70,US
1,Buick Skylark 320,15.0,8,350.0,165.0,3693.0,11.5,70,US
2,Plymouth Satellite,18.0,8,318.0,150.0,3436.0,11.0,70,US
3,AMC Rebel SST,16.0,8,304.0,150.0,3433.0,12.0,70,US
4,Ford Torino,17.0,8,302.0,140.0,3449.0,10.5,70,US

In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]], dtype=np.float32)
print(a.ndim, a.shape, a.dtype)

2 (2, 3) float32

In [8]:
import numpy as np 
a = np.array([[[1,2,3]]], dtype=np.float32) 
print(a.ndim, a.shape, a.dtype)

3 (1, 1, 3) float32

In [11]:
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [38]:
a = np.array([1,2,3,4,5,6])
a = a.reshape(2,3)
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [17]:
current_dict = {"a":1,"b":2,"c":{"d":3,"e":4,"f":{"g":5,"h":6}}}

last_keys = []

while isinstance(current_dict, dict) and current_dict:
    keys = list(current_dict.keys())
    last_key = keys[-1] 
    last_keys.append(last_key)
    current_dict = current_dict[last_key]          

brackets_number = len(last_keys)
print(f"There are {brackets_number} nested layers")

There are 3 nested layers

In [9]:
b = np.arange(10).reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

            MPG   Weight
MPG     1.00000 -0.78751
Weight -0.78751  1.00000

In [ ]:
b = b.transpose((0,1))
b
# b = b.T is the same with b=b.transpose((0,1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [94]:
c = np.sqrt(b)
bool_index = c > 1.5
c[bool_index]

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131,
       2.82842712, 3.        ])

In [ ]:
df.describe()
Horsepower_sum = df["Horsepower"].sum()
Horsepower_min_max_median =df.describe().loc[["min","max","50%"], "Horsepower"]
Horsepower_mode =df["Horsepower"].mode()
print("Sum:" , Horsepower_sum,
      "Min:" , Horsepower_min_max_median["min"],
      "Max:" , Horsepower_min_max_median["max"],
      "Median:" , Horsepower_min_max_median["50%"],
      "Mode:" , Horsepower_mode[0]
      )

print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)
print(origin.dtype)


arrays = {
    "car": car,
    "mpg": mpg,
    "cylinders": cylinders,
    "displacement": displacement,
    "horsepower": horsepower,
    "weight": weight,
    "acceleration": acceleration,
    "model": model,
    "origin": origin
}

for name, array in arrays.items():
    print(name + ":", array.ndim, "dimension")

In [ ]:
#Create a new pandas dataframe that has the average mpg, weight, and horsepower per country of origin

mpg_groupby = df.groupby("Origin")["MPG"].mean()
weight_groupby = df.groupby("Origin")["Weight"].mean()
hoursepower_groupby = df.groupby("Origin")["Horsepower"].mean()

new_df = pd.DataFrame(print(mpg_groupby, weight_groupby, hoursepower_groupby))
new_df

In [159]:
select_more = np.array([[3,2,1],
                      [4,5,6],
                      [7,8,9]])
some_more = select_more[:, -1]
print("return array", some_more)

return array [1 6 9]

In [ ]:
import numpy as np
import pandas as pd

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])

#Create a new pandas dataframe that has the average mpg, weight, and horsepower per country of origin



grouped = df.groupby("Origin")
avg_mpg = grouped["MPG"].mean()
avg_weight = grouped["Weight"].mean()
avg_horsepower = grouped["Horsepower"].mean()
avg_df = pd.DataFrame({
    "Average MPG": avg_mpg,
    "Average Weight": avg_weight,
    "Average Horsepower": avg_horsepower
})

print(avg_df)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001A4469F2F50>